### ISSUE TITLE
Handle Contacts Intent

### ISSUE THREAD

**Issue by Myzel394** [Bnyro/ConnectYou#189]
### Steps to reproduce

I just realized that Connect You doesn't handle a contacts picker.

1. Open an app that picks a contact
2. Doesn't work :/

### Expected behavior

Should work

### Actual behavior

Current app crashes.

### Connect You version

5.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Myzel394** [comment]
I came across this issue while developing my own app in Flutter, here's some logs, but not sure if they help you:

```
E/MethodChannel#me.schlaubi.contactpicker(13007): Failed to handle method call
E/MethodChannel#me.schlaubi.contactpicker(13007): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK dat=content://com.android.contacts/... }
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2211)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1845)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at android.app.Activity.startActivityForResult(Activity.java:5554)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at android.app.Activity.startActivityForResult(Activity.java:5473)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:709)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at me.schlaubi.fluttercontactpicker.ContactPicker.requestPicker(ContactPicker.kt:39)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at me.schlaubi.fluttercontactpicker.ContactPicker.<init>(ContactPicker.kt:30)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at me.schlaubi.fluttercontactpicker.ContactPicker.<init>(Unknown Source:0)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at me.schlaubi.fluttercontactpicker.ContactPicker$Companion.requestPicker(ContactPicker.kt:264)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at me.schlaubi.fluttercontactpicker.AbstractFlutterContactPickerPlugin.onMethodCall(AbstractFlutterContactPickerPlugin.kt:28)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at android.app.ActivityThread.main(ActivityThread.java:7937)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#me.schlaubi.contactpicker(13007): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by Bnyro** [comment]
You tested a debug build after https://github.com/Bnyro/ConnectYou/commit/51d7f32e595618f35bc785bcff02444e0a6679a0 ?

**Comment by Bnyro** [comment]
At least for me, it works in the debug builds.

**Comment by Myzel394** [comment]
Oops sorry no I didn't. Are there pre build APKs available or do I need to build them myself?

**Comment by Bnyro** [comment]
https://github.com/Bnyro/ConnectYou/actions/runs/5359053148
